### ISSUE TITLE
Add shortcuts for BigBlueButton

### ISSUE THREAD

**Issue by GhaziTriki** [waldobronchart/ShortcutMapper#44]
Hello,

BigBlueButton is an open source web-conferencing system for distance learning. The application is fully accessible and we want to add the accessibility keymap. Are you happy for us to prepare a pull request?

**Comment by waldobronchart** [comment]
Hi Ghazi. Sure. How many shortcuts does this application have? Also, Is there a fork where I can look at the current implementation?
